In [79]:
import pandas as pd
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [6]:
data = pd.read_csv(r"C:\Users\Kehinde\Downloads\dirty_cafe_sales.csv")
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [23]:
#Checking for non-values
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [24]:
data['Transaction Date'].value_counts()

Transaction Date
UNKNOWN       159
ERROR         142
2023-02-06     40
2023-06-16     40
2023-03-13     39
             ...
2023-09-24     15
2023-07-30     15
2023-03-11     14
2023-07-22     14
2023-02-17     14
Name: count, Length: 367, dtype: int64

In [27]:
data['Transaction Date'] = data['Transaction Date'].replace(['UNKNOWN', 'ERROR'], pd.NA)

In [28]:
data['Transaction Date'].value_counts()

Transaction Date
2023-02-06    40
2023-06-16    40
2023-03-13    39
2023-07-21    39
2023-07-24    39
              ..
2023-09-24    15
2023-07-30    15
2023-03-11    14
2023-07-22    14
2023-02-17    14
Name: count, Length: 365, dtype: int64

In [29]:
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [31]:
data.dropna(subset=['Transaction Date'], inplace=True)

In [32]:
#Converting date column to datetime data type
data['Transaction Date']= pd.to_datetime(data['Transaction Date'])

In [33]:
data.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              9225 non-null   str
 2   Quantity          9405 non-null   str
 3   Price Per Unit    9375 non-null   str
 4   Total Spent       9383 non-null   str
 5   Payment Method    7101 non-null   str
 6   Location          6422 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), str(7)
memory usage: 670.8 KB

In [34]:
data['Item'].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      329
ERROR        283
Name: count, dtype: int64

In [39]:
#Replace all ERROR in data['Item'] to UNKNOWN
data['Item'] = data['Item'].replace({'ERROR': 'UNKNOWN'})

In [38]:
# Fill null values as UNKNOWN
data['Item'] = data['Item'].fillna('UNKNOWN')

In [40]:
data.isna().sum()

Transaction ID         0
Item                   0
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [41]:
data['Location'].value_counts()

Location
Takeaway    2889
In-store    2872
ERROR        341
UNKNOWN      320
Name: count, dtype: int64

In [43]:
#Replace all ERROR in data['Location'] to UNKNOWN
data['Location'] = data['Location'].replace({'ERROR': 'UNKNOWN'})

In [44]:
data['Location'].value_counts()

Location
Takeaway    2889
In-store    2872
UNKNOWN      661
Name: count, dtype: int64

In [45]:
data.isna().sum()

Transaction ID         0
Item                   0
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [46]:
data['Location'] = data['Location'].fillna('UNKNOWN')

In [47]:
data['Location'].value_counts()

Location
UNKNOWN     3779
Takeaway    2889
In-store    2872
Name: count, dtype: int64

In [48]:
data['Payment Method'].value_counts()

Payment Method
Digital Wallet    2197
Credit Card       2170
Cash              2158
ERROR              296
UNKNOWN            280
Name: count, dtype: int64

In [49]:
#Replace all ERROR in data['Payment Method'] to UNKNOWN
data['Payment Method'] = data['Payment Method'].replace({'ERROR': 'UNKNOWN'})

In [50]:
data.isna().sum()

Transaction ID         0
Item                   0
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location               0
Transaction Date       0
dtype: int64

In [51]:
data['Payment Method'] = data['Payment Method'].fillna('UNKNOWN')

In [52]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity            135
Price Per Unit      165
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [53]:
data['Quantity'].value_counts()

Quantity
5          1914
2          1892
4          1774
3          1766
1          1740
UNKNOWN     160
ERROR       159
Name: count, dtype: int64

In [54]:
data['Quantity'] = data['Quantity'].replace(['ERROR', 'UNKNOWN'], 1)

In [55]:
data['Quantity'].value_counts()

Quantity
5    1914
2    1892
4    1774
3    1766
1    1740
1     319
Name: count, dtype: int64

In [56]:
data['Price Per Unit'].value_counts()

Price Per Unit
3.0        2319
4.0        2219
2.0        1185
5.0        1150
1.0        1088
1.5        1073
ERROR       186
UNKNOWN     155
Name: count, dtype: int64

In [57]:
data['Price Per Unit'] = data['Price Per Unit'].replace(['ERROR', 'UNKNOWN'], 1.0)

In [59]:
data['Quantity'] = pd.to_numeric(data['Quantity'], errors='coerce')

In [60]:
data['Price Per Unit'] = pd.to_numeric(data['Price Per Unit'], errors='coerce')

In [61]:
data.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              9540 non-null   str
 2   Quantity          9405 non-null   float64
 3   Price Per Unit    9375 non-null   float64
 4   Total Spent       9383 non-null   str
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 670.8 KB

In [62]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity            135
Price Per Unit      165
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [67]:
#Fill with mean or median but since there isn't outliers we fill with mean 
data['Quantity'] = data['Quantity'].fillna(data['Quantity'].mean())

In [69]:
#Fill with mean or median but since there isn't outliers we fill with mean 
data['Price Per Unit'] = data['Price Per Unit'].fillna(data['Price Per Unit'].mean())

In [70]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [71]:
data['Total Spent'] = data['Quantity'] * data['Price Per Unit']

In [72]:
data.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [73]:
data.duplicated().sum()

np.int64(0)

In [74]:
#Saving DataFrame to CSV 
data.to_csv('cleaned_cafe_sales.csv', index=False)

Transaction ID  Item      Quantity  Price Per Unit  Total Spent  Payment Method  Location  Transaction Date
TXN_1961373     Coffee    2.0       2.000000        4.00000      Credit Card     Takeaway  2023-09-08          1
TXN_4977031     Cake      4.0       3.000000        12.00000     Cash            In-store  2023-05-16          1
TXN_4271903     Cookie    4.0       1.000000        4.00000      Credit Card     In-store  2023-07-19          1
TXN_7034554     Salad     2.0       5.000000        10.00000     UNKNOWN         UNKNOWN   2023-04-27          1
TXN_3160411     Coffee    2.0       2.000000        4.00000      Digital Wallet  In-store  2023-06-11          1
                                                                                                              ..
TXN_7672686     Coffee    2.0       2.000000        4.00000      UNKNOWN         UNKNOWN   2023-08-30          1
TXN_9659401     UNKNOWN   3.0       2.879093        8.63728      Digital Wallet  UNKNOWN   2023-06-02          1
TXN_5255387     Coffee    4.0       2.000000        8.00000      Digital Wallet  UNKNOWN   2023-03-02          1
TXN_7695629     Cookie    3.0       2.879093        8.63728      Digital Wallet  UNKNOWN   2023-12-02          1
TXN_6170729     Sandwich  3.0       4.000000        12.00000     Cash            In-store  2023-11-07          1
Name: count, Length: 9540, dtype: int64

In [80]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11